Sunbird-Knowlg/sunbird-pdf-player

projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/services/viewer.service.ts
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.html
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23547" title="SB-23547" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23547</a>  Enable new pdf player V2 to inside collection (mobile app)
</td></table>
<br />

Issue #SB-23547 fix: handled content to be played next in pdf player

---

projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.html
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24266" title="SB-24266" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24266</a>  Question Set : The "replay" and "exit" options are not properly aligned in the summary page
</td></table>
<br />

Issue #SB-24266 fix: Hadled exit in pdf player and updated sdk version

---

projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/pdf-viewer/pdf-viewer.component.ts
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.html
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.scss
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24334" title="SB-24334" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24334</a>  PDF player : The "page not found" error is not displayed as per invision when the user enters an invalid page number
</td></table>
<br />

Issue #SB-24334 fix: Handled invalid page in pdf player

---

projects/sunbird-pdf-player/package-lock.json
projects/sunbird-pdf-player/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24326" title="SB-24326" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-24326</a>  Mobile app: Menu & Exit option is not available on end screen for pdf and epub content
</td></table>
<br />

Issue #SB-24326 fix: updated sdk version in pdf player

---

projects/sunbird-pdf-player/package-lock.json
projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23430" title="SB-23430" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23430</a>  Media/mime type compatibility on preview at creation side 
</td></table>
<br />

Issue #SB-23430 fix: added object in error event

---

projects/sunbird-pdf-player/package-lock.json
projects/sunbird-pdf-player/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23430" title="SB-23430" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23430</a>  Media/mime type compatibility on preview at creation side 
</td></table>
<br />

 Issue #SB-23430 fix: updated sdk version to 4.0.4

---

projects/sunbird-pdf-player/package-lock.json
projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.service.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25138" title="SB-25138" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25138</a>  [Telemetry] context_env: "contentplayer" cdata should have {type: "PlayerVersion", id: "2.0"}
</td></table>
<br />

Issue #SB-25138 fix: changed env to lowercase and added player version in cdata

---

package.json
projects/sunbird-pdf-player/package-lock.json
projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/pdf-viewer/pdf-viewer.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25080" title="SB-25080" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25080</a>  sometimes its been observed that page redirection is not appropriate, when user is jumping from one page to another
</td></table>
<br />

Issue #SB-25080 fix: Removing ng destroy method

---

projects/sunbird-pdf-player/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24980" title="SB-24980" target="_blank"><img alt="Test" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10513&avatarType=issuetype" />SB-24980</a>  Test Scenarios:  SB-22889
</td></table>
<br />

sb-24980 fix: accessibility changes

---

projects/sunbird-pdf-player/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24890" title="SB-24890" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24890</a>  Accessibility: On Keyboard tab and then clicking on Enter user is not taken to that tab and also in filter fields the dropdown is not displayed
</td></table>
<br />

sb-24890 fix:portal version updated

---

README.md
projects/sunbird-pdf-player/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28108" title="SB-28108" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-28108</a>  Mobile App + Portal : Additional icon is not available below the banner.
</td></table>
<br />
* Software …

#SB-28695 feat: Doc: Hybrid App >> Content-Player integration in mobile app

---

README.md

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28695" title="SB-28695" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />SB-28695</a>  Doc: Hybrid App >> Content-Player integration in mobile app
</td></table>
<br />
* …

#SB-28695  feat: Doc: Hybrid App >> Content-Player integration in mobile app

---

README.md
package-lock.json
package.json
projects/sunbird-pdf-player/package.json
schematics/collection.json
schematics/ng-add/index.ts
schematics/ng-add/messages.ts
schematics/ng-add/schema.json
schematics/ng-add/schema.ts
schematics/ng-add/setup-project.ts
schematics/ng-add/steps/add-spp-module.ts
schematics/ng-add/steps/add-spp-style.ts
schematics/utils/package-config.ts
schematics/utils/project.ts
tsconfig.schematics.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28710" title="SB-28710" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />SB-28710</a>  Tech Item: Publishing as NG module
</td></table>
<br />

Issue #SB-28710 feat: Publishing as NG module

---

package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28710" title="SB-28710" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />SB-28710</a>  Tech Item: Publishing as NG module
</td></table>
<br />

Issue #SB-28710 fix: updated the library build command

---

README.md
projects/sunbird-pdf-player/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28710" title="SB-28710" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />SB-28710</a>  Tech Item: Publishing as NG module
</td></table>
<br />

Issue #SB-28710 fix: updated the package version

---

projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.html

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26011" title="SB-26011" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-26011</a>  Video/pdf/epub player UI enhacements
</td></table>
<br />

#SB-26011 feat: Video/pdf/epub player UI enhancements

---

projects/sunbird-pdf-player/package.json

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26011" title="SB-26011" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-26011</a>  Video/pdf/epub player UI enhacements
</td></table>
<br />

#SB-26011 feat: Updated the package version

---

.circleci/config.yml
projects/sunbird-pdf-player/package.json
sonar-project.properties

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25705" title="SB-25705" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-25705</a>  Automate the process of npm publish for sb-forms, common-components
</td></table>
<br /> …

Issue #SB-25705 chore: Updated pdf player package

---

projects/sunbird-pdf-player/src/lib/pdf-viewer/pdf-viewer.component.spec.ts
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.spec.ts

Code coverage Report Before changes
=============================== Coverage summary ===============================
Statements : 76.03% ( 257/338 )
Branches : 43.24% ( 64/148 )
Functions : 71.18% ( 42/59 )
Lines : 75.55% ( 238/315 )
Code coverage Report After the changes
=============================== Coverage summary ===============================
Statements   : 87.27% ( 295/338 )
Branches     : 59.45% ( 88/148 )
Functions    : 84.74% ( 50/59 )
Lines        : 86.66% ( 273/315 )
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-23" title="KN-23" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-23</a>  PDF player Meet the minimal code Coverage criteria …

Issue #KN-23 fix: PDF player Meet the minimal code Coverage criteria

---

projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/pdf-viewer/pdf-viewer.component.spec.ts
projects/sunbird-pdf-player/src/lib/pdf-viewer/pdf-viewer.component.ts

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-239" title="KN-239" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-239</a>  Implementation - Knowlg player app for PDF, Video and Epub player
</td></table>
<br />
* Hardware …

Issue #KN-239 fix: fixed scroll issue

---

.circleci/config.yml
README.md
build-wc.js
package-lock.json
package.json
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.spec.ts
web-component/index.html
web-component/styles.css

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-304" title="KN-304" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-304</a>  Content players V2 (PDF) Web component output updation
</td></table>
<br />

Issue #KN-304 fix: Content players V2 (PDF) Web component output updation  

---

README.md
projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.spec.ts
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.ts

Web component integration in angular App : https://drive.google.com/file/d/1cVyxCPaIQ9fblDkKyGpfcG4tC2Uokx4L/view?usp=sharing
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-304" title="KN-304" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-304</a>  Content players V2 (PDF) Web component output updation
</td></table>
<br />
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please …

Issue #KN-304 fix: Content players V2 (PDF) Web component output updation 

---

README.md

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-316" title="KN-316" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-316</a>  PDF Player angular version update from 12 to 14 with IVY
</td></table>
<br />
* Hardware …

Issue #KN-316 feat: Pdf player: web component implementation readme file updates with steps

---

README.md

<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-686" title="KN-686" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-686</a>  Create a demo for Embeddable  content player - PDF player - Part 2
</td></table>
<br />
* …

Issue #KN-686 feat: Updated readme file for integration setps for different frameworks(react, flutter, reactNative)

---

.circleci/config.yml
.gitignore
web-component-demo/index.html

Issue #KN-832 feat: Add the package and updated circleci

---

README.md
projects/sunbird-pdf-player/package.json
web-component-demo/index.html
web-component/package.json

Issue #KN-862 docs: Updated the web component integration docs

---

.circleci/config.yml
README.md
projects/sunbird-pdf-player/README.md
projects/sunbird-pdf-player/package.json
web-component/package.json

Issue #KN-862 feat: Updated the documentation and references

---

package-lock.json
projects/sunbird-pdf-player/package-lock.json
projects/sunbird-pdf-player/package.json
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.html
projects/sunbird-pdf-player/src/lib/sunbird-pdf-player.component.ts

pdf player changes to support languages

---

README.md

SBCOSS-509: Updated Readme documentation for publishing to NPM
